name: gatsby-starter

config:
  webroot: public

proxy:
  appserver:
    - gatsby-starter.lndo.site

services:
  appserver:
    type: node:14
    ssl: true
    build:
      - "cd /app && yarn install && gatsby build"
    globals:
      gatsby-cli: latest
      yarn: latest

tooling:
  yarn:
    service: appserver
  gatsby:
    service: appserver
  gatsby:develop:
    cmd: gatsby develop --host 0.0.0.0 --port 80
    service: appserver
