name: gatsby-starter

config:
  webroot: public

proxy:
  custom-gatsby:
    - gatsby-starter.lndo.site

services:
  custom-gatsby:
    ssl: true
    type: node:14
    scanner: false
    globals:
      gatsby-cli: latest
      yarn: latest

# events:
  # post-start:
  #   - custom-gatsby: "cd /app && yarn install && gatsby build"

tooling:
  yarn:
    service: custom-gatsby
  gatsby:
    service: custom-gatsby
  gatsby:develop:
    cmd: gatsby develop --host 0.0.0.0 --port 80
    service: custom-gatsby
